###
GET http://localhost:3000

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{ 
  "email": "outrctznmmkpgxqbso@sdvgeft.com",
  "password": "test",
  "firstName": "test6",
  "lastName": "test"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{ 
  "username": "outrctznmmkpgxqbso@sdvgeft.com",
  "password": "test"
}

###
POST http://localhost:3000/api/v1/auth/refresh-token
Content-Type: application/json

{ 
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0MSIsImxhc3ROYW1lIjoidGVzdCIsInJvbGVzIjpbIlBva8OpbW9uIFRyYWluZXIiXX0sImlhdCI6MTYzMTk4MjcxNCwiZXhwIjoxNjYzNTQwMzE0LCJpc3MiOiJqb2pvLXRrIn0.twwpJJTRD5XebciW7oFpMbhcIkUPzlH8sjNrnrjco-g"
}

###
POST http://localhost:3000/api/v1/auth/email-reset-password
Content-Type: application/json

{ 
  "email": "outrctznmmkpgxqbso@sdvgeft.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNDY0MmIzOTdlMjljNDhlMDEzZjI0OSIsImVtYWlsIjoib3V0cmN0em5tbWtwZ3hxYnNvQHNkdmdlZnQuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkOC9VRDdvdFdvcEtORmx6Rmt5azBJdVJ1VFVVaU1wakZZV002dXlPcnJxSDVqQ3lrTnROYWUiLCJmaXJzdE5hbWUiOiJ0ZXN0NiIsImxhc3ROYW1lIjoidGVzdCIsInJvbGVzIjpbIlBva8OpbW9uIFRyYWluZXIiXSwiY3JlYXRlZEF0IjoiMjAyMS0wOS0xOFQxOTo0OTowNy45MDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wOS0xOFQxOTo1MzozNC43MTBaIn0sImlhdCI6MTYzMTk5NDk3MCwiZXhwIjoxNjMxOTk1MjcwLCJpc3MiOiJqb2pvLXRrIn0.FgrVPbpYFwdwS2xe9WgHrXVS-xXR9vashY6KsP4aiyw
Content-Type: application/json

{ 
  "password": "test1"
}