###
GET http://localhost:3000

###
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{ 
  "email": "sdpgezixtcxaganirw@pp7rvv.com",
  "password": "12345678",
  "firstName": "test1",
  "lastName": "test"
}

###
# @name login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{ 
  "username": "sdpgezixtcxaganirw@pp7rvv.com",
  "password": "12345678"
}

###
POST http://localhost:3000/api/v1/auth/refresh-token
Content-Type: application/json

{ 
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoieGZjbndtbG1pbmt5ZHp0dHptQHBwN3J2di5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0NyIsImxhc3ROYW1lIjoidGVzdCIsInJvbGVzIjpbIlBva8OpbW9uIFRyYWluZXIiXX0sImlhdCI6MTYzMjA0OTExMCwiZXhwIjoxNjYzNjA2NzEwLCJpc3MiOiJqb2pvLXRrIn0.bkfK32Dx_KBhPmW7FPat7rXlmCzL_fjJhJliOJ3QYkA"
}

###
POST http://localhost:3000/api/v1/auth/email-reset-password
Content-Type: application/json

{ 
  "email": "sdpgezixtcxaganirw@pp7rvv.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNmE3YWM4M2ZkOTZhYWNlNDM3MzllYiIsImVtYWlsIjoic2RwZ2V6aXh0Y3hhZ2FuaXJ3QHBwN3J2di5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRWY2V6VDhuZmJjLmh3NGZTWTVJMTJlZm50VDJzd3NyRDRQZ1U0WUFMSXhnVlBTTFNLZzE4RyIsImZpcnN0TmFtZSI6InRlc3QxIiwibGFzdE5hbWUiOiJ0ZXN0Iiwicm9sZXMiOlsiUG9rw6ltb24gVHJhaW5lciJdLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTE2VDA3OjEwOjAwLjI2NloiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTE2VDA3OjEwOjQ4LjYxOVoifSwiaWF0IjoxNjM0MzY4MjYyLCJleHAiOjE2MzQzNjg0NDIsImlzcyI6Impvam8tdGsifQ.S6PmtdCJjgk1ZJ0ACvDY08bIeMKASy0u_yKhjeZy07s
Content-Type: application/json

{ 
  "password": "12345678"
}

###
@accessToken = {{login.response.body.accessToken}}

###
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
GET http://localhost:3000/api/v1/users/614602936772f543ddc15dd2
Authorization: Bearer {{accessToken}}
Content-Type: application/json
